In [1]:
# PART 8-1
# 1. Create and inspect array A
import numpy as np

A = np.arange(1, 21).reshape(4, 5)

print("A:\n", A)
print("dtype:", A.dtype)
print("ndim:", A.ndim)
print("shape:", A.shape)
print("size:", A.size)
print("itemsize:", A.itemsize)

B = A.reshape(5, 4)
print("\nB:\n", B)

A:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
dtype: int64
ndim: 2
shape: (4, 5)
size: 20
itemsize: 8

B:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [2]:
#2. Broadcasting and conditions :
a = np.array([[0.,0.,0.],
              [10.,10.,10.],
              [20.,20.,20.],
              [30.,30.,30.]])

b = np.array([0., 1., 2.])

c = a + b
print("c:\n", c)

mask = (c >= 22)
print("\nmask:\n", mask)

count = np.sum(mask)
print("\nCount of values >= 22:", count)

c:
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]

mask:
 [[False False False]
 [False False False]
 [False False  True]
 [ True  True  True]]

Count of values >= 22: 4


In [3]:
#3. Grades statistics :
grades = np.array([[87, 96, 70],
                   [100, 87, 90],
                   [94, 77, 90],
                   [100, 81, 82]])

print("Sum:", np.sum(grades))
print("Min:", np.min(grades))
print("Max:", np.max(grades))
print("Mean:", np.mean(grades))
print("Std:", np.std(grades))
print("Var:", np.var(grades))

print("\nMean per column:", np.mean(grades, axis=0))
print("Mean per row:", np.mean(grades, axis=1))
print("Max per row:", np.max(grades, axis=1))

Sum: 1054
Min: 70
Max: 100
Mean: 87.83333333333333
Std: 8.792357792739987
Var: 77.30555555555556

Mean per column: [95.25 85.25 83.  ]
Mean per row: [84.33333333 92.33333333 87.         87.66666667]
Max per row: [ 96 100  94 100]


In [4]:
#4. Custom 3×3 array :
arr = np.array([[2, 4, 6],
                [1, 3, 5],
                [7, 9, 11]])

print("Row sums:", np.sum(arr, axis=1))
print("Column sums:", np.sum(arr, axis=0))
print("Overall mean:", np.mean(arr))

Row sums: [12  9 27]
Column sums: [10 16 22]
Overall mean: 5.333333333333333


In [5]:
#5. Array operations :
A = np.array([[10, 20, 30],
              [40, 50, 60]])

B = np.array([1, 2, 3])

print("A + B:\n", A + B)
print("\nA * 2:\n", A * 2)
print("\nA - 5:\n", A - 5)

A + B:
 [[11 22 33]
 [41 52 63]]

A * 2:
 [[ 20  40  60]
 [ 80 100 120]]

A - 5:
 [[ 5 15 25]
 [35 45 55]]


In [6]:
#6. Index operations :
grades = np.array([[70, 85, 90],
                   [88, 76, 95],
                   [60, 80, 72]])

# Index of largest value in whole array
print("Index of max (flattened):", np.argmax(grades))

# Convert to 2D index
print("2D index of max:", np.unravel_index(np.argmax(grades), grades.shape))

# Highest grade in each row
print("Index of max per row:", np.argmax(grades, axis=1))

# Lowest grade in each column
print("Index of min per column:", np.argmin(grades, axis=0))

Index of max (flattened): 5
2D index of max: (np.int64(1), np.int64(2))
Index of max per row: [2 2 1]
Index of min per column: [2 1 2]


In [7]:
# PART 8-2
#1. Create the 2D NumPy array :
import numpy as np
table = np.array([
    [5, 8, 2, 7],
    [1, 9, 4, 3],
    [6, 0, 11, 10],
    [12, 13, 14, 15]
])

In [8]:
second_row = table[1]
print(second_row)

[1 9 4 3]


In [9]:
third_column = table[:, 2]
print(third_column)

[ 2  4 11 14]


In [10]:
sub_table = table[1:3, 1:3]
print(sub_table)

[[ 9  4]
 [ 0 11]]


In [11]:
#2. Students’ scores (NumPy slicing) :
import numpy as np

scores = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 79],
    [55, 65, 72]
])

In [12]:
scores[:, 1] += 5
print(scores)

[[70 85 90]
 [60 80 85]
 [88 97 79]
 [55 70 72]]


In [13]:
scores[0] = [100, 100, 100]
print(scores)

[[100 100 100]
 [ 60  80  85]
 [ 88  97  79]
 [ 55  70  72]]


In [14]:
scores[:, 2] = 0
print(scores)

[[100 100   0]
 [ 60  80   0]
 [ 88  97   0]
 [ 55  70   0]]


In [15]:
#3. Array operations :
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

v = np.array([2, 4])

In [16]:
print(A * B)

[[ 5 12]
 [21 32]]


In [17]:
print(A @ B)

[[19 22]
 [43 50]]


In [18]:
print(A * v)

[[ 2  8]
 [ 6 16]]


In [19]:
# 4. Random matrix + unique values :
# A) Random matrix :
np.random.seed(0)

matrix = np.random.randint(-5, 6, (4, 4))
print(matrix)

[[ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [-3 -1  2  1]
 [ 3  3  5 -4]]


In [20]:
# Unique values + counts :
values, counts = np.unique(matrix, return_counts=True)
print(values)
print(counts)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[1 1 1 3 1 2 1 2 2 1 1]


In [21]:
# Unique rows :
unique_rows = np.unique(matrix, axis=0)
print(unique_rows)

[[-3 -1  2  1]
 [ 0 -5 -2 -2]
 [ 2  4 -2  0]
 [ 3  3  5 -4]]


In [22]:
# B) Given array :
a = np.array([
    [1, 0, 0],
    [1, 0, 0],
    [2, 3, 4]
])

In [23]:
# Unique rows :
print(np.unique(a, axis=0))

[[1 0 0]
 [2 3 4]]


In [24]:
# 5. Indexing & reshaping :
x = np.array([2, 0, 1, 5, 4, 1, 9])

A = np.array([
    [3, 8, 1],
    [6, 2, 9]
])

In [25]:
# Argsort + sorted array :
indices = np.argsort(x)
print(indices)
print(x[indices])

[1 2 5 0 4 3 6]
[0 1 1 2 4 5 9]


In [26]:
# Minimum value location in A :
pos = np.unravel_index(A.argmin(), A.shape)
print(pos)

(np.int64(0), np.int64(2))


In [27]:
# Indices where x > 3 :
print(np.where(x > 3))

(array([3, 4, 6]),)


In [28]:
# Split x into parts :
parts = np.split(x, [2, 5])
print(parts)

[array([2, 0]), array([1, 5, 4]), array([1, 9])]


In [29]:
# Expand and squeeze :
expanded = np.expand_dims(x, axis=0)
print(expanded.shape)

squeezed = np.squeeze(expanded)
print(squeezed.shape)

(1, 7)
(7,)
